"""Tambua ships no images, so the folder someone points at is the whole input (#53).

Every problem with that folder must be reported *before* training, naming the
folder and the fix. Finding out afterwards that half a class was unreadable
wastes the run and hides the cause.

The images here are generated by `support.images` -- deterministic, licence-free
and offline. That is the legitimate use for drawn shapes: asserting the pipeline
runs. They are never offered to a user as data.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("tambua", reason="the application is not installed in this environment")

from support.images import make_placeholder
from tambua.data import (
    MIN_IMAGES_PER_CLASS,
    inspect_folder,
    render_problems,
)

CLASSES = ("widget_ok", "widget_cracked")


def _populate(root: Path, class_key: str, count: int, size: int = 224) -> Path:
    folder = root / class_key
    folder.mkdir(parents=True, exist_ok=True)
    for i in range(count):
        make_placeholder(class_key, variant=i, size=size).save(folder / f"img_{i:02d}.png")
    return folder


def test_a_good_folder_reports_nothing(tmp_path: Path) -> None:
    for key in CLASSES:
        _populate(tmp_path, key, 5)
    assert inspect_folder(str(tmp_path), CLASSES) == []


def test_a_missing_folder_is_reported(tmp_path: Path) -> None:
    problems = inspect_folder(str(tmp_path / "absent"), CLASSES)
    assert len(problems) == 1
    assert "is not a directory" in problems[0].problem


def test_an_empty_folder_names_the_classes_it_wants(tmp_path: Path) -> None:
    problems = inspect_folder(str(tmp_path), CLASSES)
    assert "contains no subfolders" in problems[0].problem
    for key in CLASSES:
        assert key in problems[0].remedy


def test_a_class_with_too_few_images_is_reported(tmp_path: Path) -> None:
    _populate(tmp_path, "widget_ok", 5)
    _populate(tmp_path, "widget_cracked", MIN_IMAGES_PER_CLASS - 1)

    problems = inspect_folder(str(tmp_path), CLASSES)
    assert len(problems) == 1
    assert "widget_cracked" in problems[0].where
    assert f"has {MIN_IMAGES_PER_CLASS - 1} usable image" in problems[0].problem


def test_a_configured_class_with_no_folder_is_reported(tmp_path: Path) -> None:
    """A class with no examples can never be predicted, so silence would mislead."""

    _populate(tmp_path, "widget_ok", 5)
    problems = inspect_folder(str(tmp_path), CLASSES)
    assert any('no folder for configured class "widget_cracked"' in p.problem for p in problems)


def test_a_folder_the_config_does_not_define_is_reported(tmp_path: Path) -> None:
    """Otherwise a typo in a folder name silently trains a label nothing describes."""

    for key in CLASSES:
        _populate(tmp_path, key, 5)
    _populate(tmp_path, "widget_crackd", 5)

    problems = inspect_folder(str(tmp_path), CLASSES)
    assert any("is not a class in the loaded configuration" in p.problem for p in problems)


def test_an_unreadable_file_is_reported_not_skipped(tmp_path: Path) -> None:
    for key in CLASSES:
        _populate(tmp_path, key, 5)
    (tmp_path / "widget_ok" / "notes.txt").write_bytes(b"this is not an image")

    problems = inspect_folder(str(tmp_path), CLASSES)
    assert any("could not be read as an image" in p.problem for p in problems)


def test_images_below_the_backbone_input_size_are_reported(tmp_path: Path) -> None:
    """Upscaling a thumbnail invents detail the camera never captured."""

    _populate(tmp_path, "widget_ok", 5)
    _populate(tmp_path, "widget_cracked", 5, size=64)

    problems = inspect_folder(str(tmp_path), CLASSES)
    assert any("smaller than 224px" in p.problem for p in problems)


def test_every_problem_names_a_location_and_a_remedy(tmp_path: Path) -> None:
    """The guarantee, checked across every failure mode at once."""

    _populate(tmp_path, "widget_ok", 1)
    _populate(tmp_path, "unknown_class", 5, size=32)
    (tmp_path / "widget_ok" / "broken.png").write_bytes(b"not an image")

    problems = inspect_folder(str(tmp_path), CLASSES)
    assert problems
    for problem in problems:
        assert problem.where, "every problem must name where it is"
        assert problem.problem, "every problem must say what is wrong"
        assert problem.remedy, f"no remedy offered for: {problem.problem}"

    rendered = render_problems(problems)
    for problem in problems:
        assert problem.where in rendered
        assert problem.remedy in rendered


def test_loading_a_bad_folder_raises_before_training(tmp_path: Path) -> None:
    """The engine must refuse the folder, not train on what it can salvage."""

    from tambua import TambuaEngine, bundled_config
    from tambua.engine import ImageFolderError

    engine = TambuaEngine(bundled_config("maize"))
    _populate(tmp_path, engine.cfg.labels[0], 1)

    with pytest.raises(ImageFolderError) as caught:
        engine.load_images_from_dir(str(tmp_path))
    assert "usable image" in str(caught.value)
