"""Bundled assets for AdaptShot.

The ONNX backbone that makes inference torch-free (`mobilenet_v3_small`, 4.0 MB;
generated by ``scripts/export_backbones.py``), and sixteen real leaf
photographs: twelve maize for the README quickstart, four more for the offline
conference demo. None of it needs a download. The
photographs are PlantVillage's, not ours; ``samples/README.md`` carries their
licence, citation and checksums.
"""

from __future__ import annotations

from pathlib import Path

_SAMPLES = Path(__file__).resolve().parent / "samples"


def sample_images() -> tuple[list[str], list[str]]:
    """Paths and labels of the bundled maize photographs, sorted, four per class.

    Returns:
        ``(paths, labels)`` -- parallel lists, sorted by filename, so the split
        a caller takes is the same on every machine. The label is the class
        directory the image came from: ``gray_leaf_spot``, ``healthy_maize`` or
        ``northern_leaf_blight``.

    Raises:
        FileNotFoundError: If the samples did not ship with this install, which
            would mean a wheel built without its package data.
    """

    paths = sorted(str(path) for path in _SAMPLES.glob("*.jpg"))
    if not paths:
        raise FileNotFoundError(
            f"no sample images under {_SAMPLES}; this install is missing its package data"
        )
    labels = [Path(path).stem.rsplit("_", 1)[0] for path in paths]
    return paths, labels


def demo_images() -> list[str]:
    """The four query photographs the offline demo walks through, in order.

    Three held-out maize leaves and one healthy tomato leaf -- a query from a
    crop the model has never seen. They were chosen because, against the twelve
    support photographs, they show a progression: a singleton prediction set, a
    two-class set, a wrong top-1 whose set still contains the true class, and a
    refusal. Which exact outcome each produces is sensitive to the support set
    -- removing one support photo moved two of them when this was measured --
    so ``examples/demo/demo.py`` assumes nothing and narrates whatever it gets.
    """

    paths = sorted(str(path) for path in (_SAMPLES / "demo").glob("*.jpg"))
    if len(paths) != 4:
        raise FileNotFoundError(
            f"expected 4 demo images under {_SAMPLES / 'demo'}, found {len(paths)}; "
            "this install is missing its package data"
        )
    return paths


__all__ = ["demo_images", "sample_images"]
