"""Bundled assets for AdaptShot.

The ONNX backbone that makes inference torch-free (`mobilenet_v3_small`, 4.0 MB;
generated by ``scripts/export_backbones.py``), and nine real maize-leaf
photographs so that the README quickstart runs with no download at all. The
photographs are PlantVillage's, not ours; ``samples/README.md`` carries their
licence, citation and checksums.
"""

from __future__ import annotations

from pathlib import Path

_SAMPLES = Path(__file__).resolve().parent / "samples"


def sample_images() -> tuple[list[str], list[str]]:
    """Paths and labels of the bundled photographs, sorted, three per class.

    Returns:
        ``(paths, labels)`` -- parallel lists, sorted by filename, so the split
        a caller takes is the same on every machine. The label is the class
        directory the image came from: ``gray_leaf_spot``, ``healthy_maize`` or
        ``northern_leaf_blight``.

    Raises:
        FileNotFoundError: If the samples did not ship with this install, which
            would mean a wheel built without its package data.
    """

    paths = sorted(str(path) for path in _SAMPLES.glob("*.jpg"))
    if not paths:
        raise FileNotFoundError(
            f"no sample images under {_SAMPLES}; this install is missing its package data"
        )
    labels = [Path(path).stem.rsplit("_", 1)[0] for path in paths]
    return paths, labels


__all__ = ["sample_images"]
