"""ONNX Runtime backend for lightweight feature extraction.

Uses pre-exported ONNX backbone models bundled with the package.
No PyTorch required – ideal for fast installation and edge deployment.

The ONNX models are generated by: python scripts/export_backbones.py
"""

from __future__ import annotations

import logging
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict

import numpy as np
from PIL import Image

try:
    import onnxruntime as ort

    ONNX_AVAILABLE = True
except ImportError:  # pragma: no cover – onnxruntime is optional
    ONNX_AVAILABLE = False

logger = logging.getLogger(__name__)

_MODEL_DIR = Path(__file__).resolve().parent.parent.parent / "data"

_ONNX_MODEL_FILES: Dict[str, str] = {
    "resnet18": "resnet18.onnx",
    "mobilenet_v3_small": "mobilenet_v3_small.onnx",
}

_OUTPUT_DIM: Dict[str, int] = {
    "resnet18": 512,
    "mobilenet_v3_small": 576,
}

_IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
_IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)


class ONNXBackend:
    """Feature extraction using ONNX Runtime with bundled backbone models."""

    def __init__(self) -> None:
        if not ONNX_AVAILABLE:
            raise ImportError(
                "onnxruntime is not installed. Run: pip install onnxruntime"
            )

    @lru_cache(maxsize=4)
    def _get_session(self, backbone_name: str) -> Any:
        """Load and cache an ONNX inference session for the given backbone."""
        if backbone_name not in _ONNX_MODEL_FILES:
            raise ValueError(
                f"Unknown backbone: {backbone_name}. "
                f"Available: {list(_ONNX_MODEL_FILES.keys())}"
            )
        model_path = _MODEL_DIR / _ONNX_MODEL_FILES[backbone_name]
        if not model_path.exists():
            raise FileNotFoundError(
                f"ONNX model not found: {model_path}. "
                f"Run scripts/export_backbones.py to generate it, "
                f"or install with: pip install 'adaptshot[torch]'"
            )
        logger.info("Loading ONNX backbone from %s", model_path)
        return ort.InferenceSession(
            str(model_path), providers=["CPUExecutionProvider"]
        )

    def extract(
        self, pil_image: Image.Image, backbone_name: str
    ) -> np.ndarray:
        """Run inference and return the feature embedding as a numpy array."""
        session = self._get_session(backbone_name)
        input_tensor = self._preprocess(pil_image)
        input_name = session.get_inputs()[0].name
        outputs = session.run(None, {input_name: input_tensor})
        return outputs[0].squeeze(0)  # type: ignore[no-any-return]

    @staticmethod
    def _preprocess(pil_image: Image.Image) -> np.ndarray:
        """Apply ImageNet-standard preprocessing: resize → normalize → NCHW."""
        img = pil_image.resize((224, 224), Image.BILINEAR)  # type: ignore[attr-defined]
        img_array = np.asarray(img, dtype=np.float32) / 255.0
        img_array = (img_array - _IMAGENET_MEAN) / _IMAGENET_STD
        img_array = np.transpose(img_array, (2, 0, 1)).astype(np.float32)
        return img_array[np.newaxis, ...]

    @property
    def output_dim(self) -> Dict[str, int]:
        """Return the embedding dimensionality for each supported backbone."""
        return dict(_OUTPUT_DIM)
